# Generated by Django 5.1 on 2024-10-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhosOnAux', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendees',
        ),
    ]
