# Generated by Django 5.1 on 2024-09-20 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhosOnAux', '0002_playlist_rename_host_party_host_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.IntegerField()),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhosOnAux.party')),
            ],
        ),
    ]
