# Generated by Django 5.1 on 2024-10-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WhosOnAux", "0004_alter_attendees_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendees",
            name="status",
            field=models.CharField(
                choices=[
                    ("NR", "No response"),
                    ("Y", "Yes"),
                    ("N", "No"),
                    ("MAYBE", "Maybe"),
                ],
                default="NR",
                max_length=12,
            ),
        ),
    ]
