# Generated by Django 5.1 on 2024-10-03 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WhosOnAux", "0005_alter_attendees_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendees",
            old_name="party_id",
            new_name="party",
        ),
    ]
