# Generated by Django 5.1 on 2024-10-03 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WhosOnAux", "0009_attendees"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendees",
        ),
    ]
